# frozen_string_literal: true

# 389. Find the Difference
# Easy
# https://leetcode.com/problems/find-the-difference

=begin
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
=end

# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
  (s + t).bytes.reduce(:^).chr
end

# **************** #
#       TEST       #
# **************** #

require "test/unit"
class Test_find_the_difference < Test::Unit::TestCase
  def test_
    assert_equal "e", find_the_difference("abcd", "abcde")
    assert_equal "y", find_the_difference("", "y")
  end
end
